config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :events
  resources :students do
    collection { post :import }
  end
  resources :scans

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :scans, dependent: :destroy
  has_many :students, through: :scans
  validates :title, presence: true
end

app/models/scan.rb
class Scan < ApplicationRecord
  belongs_to :event
  belongs_to :student
  validates :student_id, presence: true
  validates :event_id, presence: true

  def self.as_csv
    header = %w[id last first scan_time notes]
    CSV.generate do |csv|
      csv << header
      all.each do |scan|
        csv << [
          scan.student_id,
          scan.student.last,
          scan.student.first,
          scan.created_at,
          scan.notes
        ]
      end
    end
  end

end

app/models/student.rb
class Student < ApplicationRecord
  has_many :scans, dependent: :destroy
  has_many :events, through: :scans
  validates :first, presence: true
  validates :last,  presence: true
  validates :year,  presence: true
  validates :id,   presence: true

  #import passing file as arg
  def self.import(file)
    CSV.foreach(file, :headers => true) do |row|
      id, first, last, year = row
      Student.create!(row.to_hash)
    end
  end

  def full_name
    "#{last}, #{first} - Class of #{year}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", except: [:index]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @scans = @event.scans.all
    @scan = Scan.new

    respond_to do |format|
      format.html
      format.csv {send_data @scans.as_csv, filename: "#{@event.title}-#{Date.today}.csv" }
    end
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "Successful event creation!"
      redirect_to @event
    else
      render 'new'
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  private
    def event_params
      params.require(:event).permit(:title, :start)
    end

end

app/controllers/scans_controller.rb
class ScansController < ApplicationController

  def new
  end

  def edit
    @scan = Scan.find(params[:id])
  end

  # build scan into student and event ids
  def create
    # if barcode scanner input, marked by "?" at end of string,
    # this first line will select the ID part of the input
    if params[:scan][:student_id].last == "?"
      params[:scan][:student_id] = params[:scan][:student_id][7...15]
    end
    @event = Event.find(params[:scan][:event_id])
    @student = Student.find(params[:scan][:student_id])
    @scan = @event.scans.build(scan_params)
    if @scan.save
      flash[:success] = "Successful entry!"
      redirect_to @event
    else
      flash[:danger] = "Scan NOT successful!"
      redirect_to @event
    end
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = "Student NOT found!"
    redirect_to @event
  end

  def update
    @scan = Scan.find(params[:id])
    if @scan.update(scan_params)
      redirect_to @scan.event
    else
      render 'edit'
    end
  end

  def destroy
  end

  private
    def scan_params
      params.require(:scan).permit(:notes, :student_id, :event_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

  def index
    @students = Student.all
  end

  def import
    Student.import(params[:file].path)
    flash[:success] = "Students Imported!"
  rescue NoMethodError
    flash[:danger] = "No file selected!"
  rescue ActiveRecord::RecordNotUnique
    flash[:danger] = "There was a Student ID conflict!"
    redirect_to students_path
  end

  def show
    @student = Student.find(params[:id])
    @scans = @student.scans.all
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:success] = "Successful student creation!"
      redirect_to @student
    else
      render 'new'
    end
  rescue ActiveRecord::RecordNotUnique => e
    flash[:danger] = "Student ID already exists!"
    redirect_to students_path
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to @student
    else
      render 'edit'
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

  private
    def student_params
      params.require(:student).permit(:first, :last, :year, :id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Attendance Scanner Application"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/scans_helper.rb
module ScansHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/events/_eventform.html.erb
<%= form_with model: @event, local: true do |f| %>

<p>
  <%= f.label :title %><br>
  <%= f.text_field  :title %>
</p>

<p>
  <%= f.label :time %><br>
  <%= f.datetime_select :start %>
</p>
<br>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/events/edit.html.erb
<% provide(:title, "Edit Event") %>

<h1>Edit Event</h1>

<%= render 'eventform', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% provide(:title, "events") %>
<div class="container">
  <h3>Listing All Events</h3>
  <h4><%= link_to 'New event', new_event_path %></h4>
  <table id="table" class="table table-striped table-bordered table-hover table-condensed">
    <tr>
      <th>Title</th>
      <th>Start time</th>
    </tr>

    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.start %></td>
        <td><%= link_to 'Show', event_path(event) %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event_path(event),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/events/new.html.erb
<% provide(:title, "New Event") %>

<h1>Create an Event</h1>

<%= render 'eventform' %>

app/views/events/show.html.erb
<% provide(:title, "events") %>
<div class="container">
  <div class="col-sm-8">
    <p><h3>
      <strong>Title: </strong>
      <%= @event.title %>
      <br>
      <strong>Start time: </strong>
      <%= @event.start %>
      <br></h3>


      <% if @event.scans.any? %>
      <h4>Scans (<%= @event.scans.count %>)</h4>
      <ol class="scans">
        <%= render @scans %>
      </ol>
      <% end %>
      <%= link_to 'Back', events_path %>
    </p>
  </div>
  <div class="col-sm-4">
    <p>
      <div class="row">
        <section id="scan_form">
          <h3>Scan Field</h3>
          <%= render 'shared/scanform' %>
          <br>
          <%= link_to "Export Scans to CSV", event_path(format: :csv)%>
          <br>
          <h3>OR</h3>
          <br>
          <h4>Add Student by Name: </h4>
          <%= render 'shared/scanbyname' %>
        </section>
      </div>
    </p>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Attendance Scanner
    by <a href="mailto:lofton@protonmail.ch">Johnny Lofton</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Help",    help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Attendance Scanner", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "View Students", students_path %></li>
        <li><%= link_to "View Events",   events_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/scans/_editscanform.html.erb
<%= form_for @scan do |f| %>
  <div class="field">
    <%= f.text_area :notes, :value => "" %>
  </div>
  <%= f.submit "Add Note", class: "btn btn-primary" %>
<% end %>

app/views/scans/_scan.html.erb
<li id="scan-<%= scan.id %>">
  <span class="student"><%= scan.student.last %>, <%= scan.student.first %>
    scanned in for
  </span>
  <span class="event">
    <%= scan.event.title %>
  </span>
  <span class="timestamp">
    <%= time_ago_in_words(scan.created_at) %> ago.
  </span>
  <span>
    <%= link_to 'Add or Edit Note', edit_scan_path(scan) %>
  </span>
  <span>
    Notes: <%= scan.notes %>
  </span>
</li>

app/views/scans/edit.html.erb
<% provide(:title, "Edit Scan") %>

<h1>Edit Scan</h1>

<%= render 'editscanform', scan: @scan %>

<%= link_to 'Cancel', event_path(@scan.event) %>

app/views/shared/_scanbyname.html.erb
<%= form_for @scan do |f| %>
  <div class="field">
    <%= f.hidden_field :notes, :value => "" %>
  </div>
  <div class="field">
    <%= f.hidden_field :event_id, :value => @event.id %>
  </div>
  <div class="field">
    <%= f.collection_select :student_id, Student.order(:last),:id, :full_name, include_blank: true %>
  </div>
  <br>
  <%= f.submit "Create Scan", class: "btn btn-primary" %>
<% end %>

app/views/shared/_scanform.html.erb
<%= form_for @scan do |f| %>
  <div class="field">
    <%= f.hidden_field :notes, :value => "" %>
  </div>
  <div class="field">
    <%= f.hidden_field :event_id, :value => @event.id %>
  </div>
  <div class="field">
    <%= f.text_field :student_id, :autofocus => true, placeholder: "Scan field" %>
  </div>
  <br>
  <%= f.submit "Scan", class: "btn btn-primary" %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="center">
  <h1>About</h1>
</div>
<h2>Technical specifications</h2>
<p>This application was created with Ruby on Rails 5.2.0 and uses SQLite3.</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="center">
  <h1>Help</h1>
  <h3>FAQ</h3>
</div>
<div class="container">
  <div class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading">Can I scan from multiple computers at a time?</div>
      <div class="panel-body">Yes, Rails uses threads for HTTP handling,
      meaning more than one machine can use
      a webpage at a time, even scanning for the same event at the same time.</div>
    </div>
  </div>
</div>
<div class="center">
<h4>
  Have a question that isn't on this list?
  <br>
  <small>
    Email your suggestion using the link in the footer!</small>
  </h4>
</div>

app/views/static_pages/home.html.erb
<div class="center">
  <h1>Welcome</h1>
  <h2>Student Attendance Scanner</h2>
  <ul class="nav flex-column nav-justified">
    <li class="nav-link active">
      <%= link_to "View Students", students_path %>
    </li>
    <li class="nav-link active">
      <%= link_to "View Events",   events_path %>
    </li>
  </ul>
</div>

app/views/students/_importform.html.erb
<%= form_tag import_students_path, multipart: true do %>
  <%= file_field_tag :file %><br><%= submit_tag "Import CSV" %>
<% end %>
<section id='csv'>
  <h3>Example CSV File:</h3>
  <table class="table table-striped table-bordered table-hover table-condensed">
    <tr>
      <th>id</th>
      <th>first</th>
      <th>last</th>
      <th>year</th>
    </tr>
    <tr>
      <th>123456</th>
      <th>jane</th>
      <th>doe</th>
      <th>2021</th>
    </tr>
    <tr>
      <th>654321</th>
      <th>john</th>
      <th>smith</th>
      <th>2020</th>
    </tr>
  </table>
</section>
<small>(you must include the first row (id, first, last, year) as shown in the example, or the attributes will not be recognized!)</small>

app/views/students/_studentform.html.erb
<%= form_with model: @student, local: true do |f| %>

<p>
  <%= f.label :first %><br>
  <%= f.text_field  :first %>
</p>

<p>
  <%= f.label :last %><br>
  <%= f.text_field  :last %>
</p>

<p>
  <%= f.label :year %><br>
  <%= f.text_field  :year %>
</p>

<p>
  <%= f.label :id %><br>
  <%= f.text_field  :id %>
</p>
<br>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/students/edit.html.erb
<% provide(:title, "Edit Student") %>

<h1>Edit Student</h1>

<%= render 'studentform', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<% provide(:title, "Students") %>
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <h3>Listing All Students (<%= @students.count %>)</h3>
      <table id="table" class="table table-striped table-bordered table-hover table-condensed">
        <tr>
          <th>ID</th>
          <th>Last</th>
          <th>First</th>
          <th>Year</th>
          <th></th>
        </tr>
        <% @students.each do |student| %>
          <tr>
            <td><%= student.id %></td>
            <td><%= student.last %></td>
            <td><%= student.first %></td>
            <td><%= student.year %></td>
            <td><%= link_to 'Show', student_path(student) %></td>
            <td><%= link_to 'Edit', edit_student_path(student) %></td>
            <td><%= link_to 'Destroy', student_path(student),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="col-sm-4">
      <h4><%= link_to 'New student', new_student_path %></h4>
      <%= render 'importform' %>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<% provide(:title, "New Student") %>

<h1>Add a new Student</h1>

<%= render 'studentform' %>

app/views/students/show.html.erb
<% provide(:title, "Students") %>
<p>
  <strong>Name: </strong>
  <%= @student.last %>, <%= @student.first %>
  <strong>Year: </strong>
  <%= @student.year %>
  <strong>ID: </strong>
  <%= @student.id %>

  <div>
    <% if @student.scans.any? %>
    <h3>Scans (<%= @student.scans.count %>)</h3>
    <ol class="scans">
      <%= render @scans %>
    </ol>
    <% end %>
  </div>

  <%= link_to 'Back', students_path %>
</p>